src/components/SwapWidget/MarketOrder/index.tsx

- for now unmount drawer in swap widget if drawer is not opened to make it more performant

swap drawer issue

---

src/components/SwapWidget/TokenListDrawer/TokenListRow.tsx
src/components/SwapWidget/TokenListDrawer/index.tsx

Fix css of "add button"
The remove a token list alert now accepts any "remove" word

Fix css and alert in "remove token list"

---

src/components/WalletModal/styles.tsx

Fixed the modal wallet color not going to the end of the modal

Fixed wallet modal

---

src/components/SwapWidget/LimitOrder/index.tsx
src/components/SwapWidget/MarketOrder/index.tsx
src/components/SwapWidget/index.tsx
src/components/SwapWidget/swapWidget.stories.tsx

Users can pass token symbols as defaultInputToken & defaultOutputToken props (case insensitive) to swap widget. 
If match is found, that token is set. Otherwise, original default tokens will be set in place.

added defaultInputToken & defaultOutputToken props to swap widget

---

src/components/Pools/AddLiquidity/PoolPriceBar/index.tsx
src/components/Pools/AddLiquidity/index.tsx
src/components/SarManageWidget/Title.tsx
src/components/SwapWidget/ConfirmSwapDrawer/index.tsx
src/components/SwapWidget/LimitOrder/index.tsx
src/components/TextInput/TextInput.tsx
src/components/TextInput/styles.tsx
src/locales/de.json
src/locales/en.json
src/locales/es.json
src/locales/fr.json
src/locales/pt-br.json
src/locales/tr.json
src/locales/vn.json
src/locales/zh.json
src/state/pswap/hooks.ts

This PR includes;
on mobile amount keyboard should be numeric -> https://app.clickup.com/t/3bufced
The title "Add liquidity" has an extra full stop in the end -> https://app.clickup.com/t/3ch99bu
The "Dollar Worth" on the "Add liquidity" menu should be "USD" -> https://app.clickup.com/t/3chhqcz
There is a spacing issue in the message on the "Trade" menu -> https://app.clickup.com/t/3chhnac
There is no space between the text "Insufficient" and "Token name" -> https://app.clickup.com/t/3cbjeye
There is an alignment issue with the Balance in Add liquidity -> https://app.clickup.com/t/3cbjv7c
Mobile Stake V2 title update -> https://app.clickup.com/t/3bufdg0
The "Select a token" form is not properly aligned and is broken. -> https://app.clickup.com/t/3cq0hfa

Fixed UI Bugs

---

src/constants/abis/pangolinPair.ts

make default import instead of named import when there is no named export in importing file

fix: import abi

---

src/index.tsx

- fix: export mixpanel hooks and enum in index.ts

fix: export mixpanel hooks and enum in index.ts

---

src/components/Bridge/BridgeCard/index.tsx
src/hooks/bridge/Chains.ts
src/state/pbridge/hooks.ts

- Get routes only if required inputs are filled.
- Cosmos Chain Names
0xSquid Side;
This feature is also related to the 0xSquid team's developments.
1- `quoteOnly` field should work with Cosmos networks. (And then need another development on our side; we don't need to wait for the Cosmos Wallet address to get the route.)
2- Their SDK-type development. One of the fields is required even if it shouldn't. They need to fix this.

fix: bridge-swap cosmos bugs

---

package.json
src/components/SwapWidget/MarketOrder/index.tsx
src/components/SwapWidget/SelectTokenDrawer/index.tsx
src/hooks/Tokens.ts
src/hooks/useWrapCallback.ts

1. The "Associate" button turns to "Associating" button and gets disabled if the user rejects the transaction
2. For the very first time the "WHBAR" token appears on the field, but there is no "WHBAR" token in the token list
3.  The fields don't set to 0.00 after successfully wrapped
4. The button shows "Insufficient HBAR balance" instead of "Enter an amount"
5. The "unwrap" button on the "Trade" card has a UI issue
https://app.clickup.com/t/86699t8er

fix: hedera ui issues

---

src/state/ppangoChef/hooks.ts

if user has not created storage then doing user related call to pangochef fails and due to that APR keeps blinking on each multicall error. issue was that storage address call was returning zero address and that check was missing, so code was assuming that user has created storage contract and it was trying to find user related farm information but in reality there was no storage contract created

fix: user storage checking issue

---

src/components/WalletModal/index.tsx
src/connectors/HashConnector/index.ts

- Removed pangolin hashpack data from local storage to fix the "secret key" error, this is probably caused by the data saved in the local storage being out of date
- now `isAuthorized` is based on `pairingData`, `encryptionKey` & `pairingData.length`. Ref: https://github.com/Hashpack/hashconnect/blob/main/lib/src/hashconnect.ts#L234-L252

fix: remove hashpack data from local storage to fix the secret key error

---

src/hooks/Tokens.ts

-  Hedera Balance blink issue in Add Liquidity Widget due to we are always trying to fetch latest balance on new block number and it will return 0/undefined while its fetching new data. so to make it not blink balance to 0 while its fetching, we are going to keep returning previously cached data

fix: balance blink issue with keeping previously cached data until new is received

---

src/state/pmulticall/updater.tsx
src/state/ppangoChef/hooks.ts

there was issue due to indexing and pid mapping. in code it was assumed that indexing will work same as pid but sometime data for all farms might not be available and index will get mismatch with pid and it will start calculating wrong aprs

fix: hedera apr pid issue

---

src/state/pwallet/hooks.ts
src/utils/hedera.ts

- When you have a nft associated in wallet it cause a multicall revert because it is querying for the decimals() function but nfts doesn't have that function, to fix this we need to query the token's metadata and check if this is fungible

fix: pools not showing in your pools

---

src/apollo/pairs.ts
src/apollo/pangochef.ts
src/components/Pools/DetailModal/Header/index.tsx
src/data/Reserves.ts
src/data/TotalSupply.ts
src/data/multiChainsHooks.ts
src/state/ppangoChef/hooks.ts
src/state/ppangoChef/types.ts

- Added Hook to use pair total supply from subgraph
- Fixed the getUser, we need to query thos data in hedera to get lockCount of farm to show locked farm warning
- Fixed the getUser call to only call if the user has staked amount in farms
- Remove rewardsSummations because is unused value
- Remove `pools()` call and replaced values from this call with values provided by subgraph
- Added reward tokens in return of useGetPangoChefInfosViaSubgraph

fix: hedera bugs and reduce more onchain calls

---

src/hooks/useContract.ts
src/index.tsx

- export more hooks and utils function to re-use it in interface repo

fix: export useful hooks and utility functions for interface

---

src/components/Pools/AddLiquidity/index.tsx
src/components/Pools/DetailModal/index.tsx
src/components/Pools/PangoChef/Compound/index.tsx
src/components/Pools/PangoChef/Stake/ConfirmDrawer.tsx
src/components/Pools/PangoChef/Stake/index.tsx
src/components/Pools/PangoChef/Stake/styleds.tsx
src/components/Pools/RemoveFarm/index.tsx
src/components/SarManageWidget/AddStake/index.tsx
src/components/SarManageWidget/Compound/index.tsx
src/components/SwapWidget/SelectTokenDrawer/index.tsx
src/hooks/Tokens.ts
src/state/pmint/actions.ts
src/state/pmint/hooks.ts
src/state/pmint/reducer.ts
src/state/pwallet/hooks.ts

- Force to add custom token when user select it, this is done so that we can search for pools with tokens that were in the token-list will be easy
- Fixed the message to create storage contract, now it only appears if user pgl greater than 0
- Fixed the all "add liquidity" fields are filled with the same value
- Added refetch interval in useGetAllHederaAssociatedTokens, we need to refetch the data because this function return the balance of associated tokens and when the user makes a swap or remove an lp, this value is not being updated
- Fixed the withdraw issue, we need to check if user is associated with pgl too, because if a user is farming in tokenA/tokenB farm and compound to PBAR/WHBAR farm it will create a lp and if the user remove from tokenA/tokenB and try to remove from …

fix: hedera & some ui bugs

---

package.json
src/components/SwapWidget/TWAP/TWAPPanel.tsx
yarn.lock

twap widget is creating issues for android users. so when android users load the page, page just goes blank. so for now implemented lazy loading twap widget so it crash will only experienced by android users if they click on TWAP tab.
see https://github.com/davidshimjs/qrcodejs/issues/159

fix: lazy load twap widget

---

src/data/TotalSupply.ts
src/data/multiChainsHooks.ts

1. Hedera Pair Totalsupply  with use of api 
2. replace hook  usePairTotalSupplyViaSubgraph with useHederaPairTotalSupply

fix: hedera pair total supply with api

---

src/components/Pools/PangoChef/ClaimReward/index.tsx
src/components/Pools/RemoveFarm/index.tsx

if PBAR not associated and when user remove farm or claim they get PBAR as reward token so need to that associate first before withdraw and claim

fix: hedera claim and remove farm associate pbar

---

src/components/Pools/PoolCard/PoolCardV1.tsx
src/data/Reserves.ts
src/data/multiChainsHooks.ts
src/hooks/multiChainsHooks.ts
src/hooks/tokens/evm.ts
src/hooks/tokens/index.ts
src/hooks/tokens/subgraph.ts
src/hooks/useCurrencyPrice.ts
src/hooks/useUSDCPrice/evm.ts
src/state/papplication/atom.ts
src/state/papplication/hooks.ts
src/state/ppangoChef/hooks/evm.ts
src/state/ppangoChef/hooks/hedera.ts
src/state/ppangoChef/hooks/index.ts
src/state/pstake/hooks/evm.ts
src/state/pwallet/hooks/evm.ts
src/state/pwallet/hooks/hedera.ts

Problem: When Subgraph stop we manually change Subgraph hooks to Contract Hooks
Solution: Now these hooks works based on "flag" set in atom so if flag changes, hooks logic will change accordingly.

fix: hedera subgraph hooks dynamically switch

---

src/apollo/pairs.ts
src/components/Pools/ClaimReward/index.tsx
src/components/Pools/DetailModal/EarnedDetail/index.tsx
src/components/Pools/DetailModal/Header/index.tsx
src/components/Pools/PangoChef/EarnDetail/index.tsx
src/components/Pools/PangoChef/Stake/index.tsx
src/components/Pools/RemoveFarm/index.tsx
src/components/Pools/Stake/index.tsx
src/state/ppangoChef/hooks/evm.ts
src/state/ppangoChef/hooks/hedera.ts
src/state/pstake/hooks/common.ts
src/state/pstake/utils.ts
src/state/pwallet/hooks/hedera.ts

- Fixed the create pairs by interface not appears, we need to refetch the subgraph query
- Fixed the extra tokens "weekly income" on hedera
- Fixed page crash when change chain and have a farm details open

fix: ui bugs related to refetch subgraph queries, extra tokens weekly income on hedera  and page crashes

---

src/components/Pools/RemoveFarm/index.tsx
src/components/Pools/RemoveLiquidity/index.tsx
src/data/multiChainsHooks.ts
src/state/papplication/atom.ts

- Changed avalanche to use pairs from subgraph, to make the swap more fast
- Reset signature in finally on "onRemove" function
- Fixed the fields in "Remove Farm" widget are collapsing

fix: ui bugs related with load swap fast, reset signature in "onRemove" and fields in remove farm are collapsing

---

src/components/Pools/AddLiquidityModal/index.tsx
src/hooks/index.tsx
src/state/ppangoChef/hooks/evm.ts
src/state/ppangoChef/hooks/hedera.ts

- Fixed still showing stake after remove all from pangochef pool
- Fixed refetch minichef farms, add chainId in query key
- Fixed the second token is not enabled in search token drawer
- https://app.clickup.com/t/3pc2g7v
- https://app.clickup.com/t/3kp9706
- https://app.clickup.com/t/8669bgmpb

fix: bugs related with refetch subgraphs, second token not enable in serach token drawer

---

src/state/papplication/atom.ts

- Reverted avalanche subgraph to use contract calls

fix: revert avalanche usepairs to contract calls

---

src/state/pwallet/hooks/hedera.ts

- Fixed `useGetHederaUserLP` hook to user pairs from subgraph

fix: hedera get pgl to user pairs from subgraph

---

src/state/pmint/elixir/hooks.ts
src/state/pmint/hooks.ts

- Fixed page crash when input a value greather max uint256
This happens when try get the amount of other token of pair using `pair.priceOf(tokenA, tokenB).quote()`, depending on the value that is in the quote it causes overflow in uint256 and enters in invariant on sdk causing the crash https://github.com/pangolindex/sdk/blob/da62dd3607e8cfef4e8b41dcc21b3be0095d6c85/src/utils.ts#L10
- https://app.clickup.com/t/866abrc67

fix: page crash when input a value greather max uint256

---

src/components/SwapWidget/MarketOrder/index.tsx
src/data/Allowances.ts
src/hooks/useApproveCallback/evm.ts
src/hooks/useApproveCallback/hedera.ts

1. Fixed the text `approving` in approve button only appears when the transaction has in app state, this take a time to disable the approve button, so theuser can send the approve transaction twice and spend gas token unnecessarily
2. Fetch the token allowance from hedera's api to the approve button appears more fast
[Approving issue.webm](https://github.com/pangolindex/components/assets/37405304/448208e8-7177-4fa3-8092-34013f2750ea)
[Load Issue.webm](https://github.com/pangolindex/components/assets/37405304/74212c99-722c-402d-94f2-5dd3e6a851dc)

fix: approve bugs

---

src/state/pwallet/hooks/hedera.ts

- Added hedera mirror node url in query key
Without it, in the first renderings the HEDERA_API_BASE_URL is api for testnet and with that we are fetching for mainnet tokens that do not exist in testnet and it makes the app not find the data and save in the cache wrong data.
- https://app.clickup.com/t/866aabpg2

fix: add hedera mirror node in query key

---

src/components/Bridge/styles.tsx

- Fixed bridge paterns logos overflow in mobile
- Before
- After

fix: bridge paterns logos overflow

---

src/components/Elixir/DetailModal/IncreasePosition/index.tsx
src/state/pburn/elixir/evm.ts
src/state/pwallet/elixir/hooks/evm.ts

- Add liquidity button will not be active any more if there is no input.
- Removed Whitespace characters from the Toast
- https://app.clickup.com/t/866afcqb4
- https://app.clickup.com/t/866afcuku

fix: elixir bugs

---

src/connectors/HashConnector/index.ts

- Fixed hashpack not connect in mobile, this happens because we don't setup the events
https://app.clickup.com/t/866agrkqw

fix: hashpack not connect in mobile

---

src/components/Pools/RemoveLiquidity/index.tsx

- Fixed approve not appears to remove liquidity, then not is possible to remove liquidity without approve the router to move the lp tokens

fix: approve not appears to remove liquidity

---

src/hooks/elixir/hooks/index.ts

- Elixir `GetPool` hook changed from Contract to Subgraph.
- https://app.clickup.com/t/85ztcg9j5

fix: changed elixir getPool hook from contract to subgraph

---

src/components/Elixir/AddLiquidity/index.tsx
src/state/pwallet/elixir/hooks/evm.ts

- The inputs still remain if got any error from the blockchain side. So the user can try it again.
- Wrong rejection error fixed
- https://app.clickup.com/t/866ajmtrh 
- https://app.clickup.com/t/866ajmrf1
- https://github.com/pangolindex/components/assets/6755848/ed12c948-5679-4531-87e7-89e20725a046
- https://github.com/pangolindex/components/assets/6755848/ed12c948-5679-4531-87e7-89e20725a046

fix: elixir bugs related to user rejection error

---

src/components/Pools/PangoChef/Stake/index.tsx
src/components/Pools/PoolCard/PoolCardView.tsx
src/components/Pools/PoolCard/PoolCardViewV3.tsx
src/components/Pools/RemoveLiquidity/index.tsx
src/components/Pools/Stake/index.tsx
src/components/SwapWidget/MarketOrder/index.tsx
src/components/SwapWidget/SwapDetailInfo/index.tsx

- Disable stake button for expired farms
- Fixed removed liquidity component is showing wrong balance
- Added tooltip in swap widget for small swap fees amount
- Wait until have approval state in swap
https://app.clickup.com/t/866akuxgb
https://app.clickup.com/t/866akuy0u
https://app.clickup.com/t/866akuw3j
https://app.clickup.com/t/866akuyam

fix: bugs related with stake in expired farms, removed liq wrong values, tootip in swap & approval state

---

src/state/airdrop/hooks.ts

- Fixed enable airdrop queries only if connected chain is same of airdrop chain

fix: enable airdrop queries only connect chain is airdrop chain

---

src/hooks/useApproveCallback/evm.ts
src/hooks/useApproveCallback/hedera.ts

- Removed useEffect in approve callback because is reseting approve state to not approved

fix: removed useeffect in approveCallback

---

package.json
src/components/DataTable/dataTable.stories.tsx
src/components/DataTable/index.tsx
src/components/DataTable/styles.tsx
src/components/DataTable/types.tsx
src/components/index.ts
src/hooks/useApproveCallback/evm.ts
src/theme/index.tsx
src/theme/styled.ts
yarn.lock

- Added DataTable Component
- https://app.clickup.com/t/862k8hrke

feat: added dataTable component

---

src/data/multiChainsHooks.ts

- Fix usepairs in avalanche to only use contract calls for now
- https://app.clickup.com/t/866apr8m1
- https://app.clickup.com/t/866apr8m1

fix: usepairs in avalanche to use contract calls

---

monorepo/package.json
monorepo/packages/shared/package.json
monorepo/packages/shared/tsconfig.json
monorepo/packages/state-hooks/package.json
monorepo/packages/state-hooks/rollup.config.js
monorepo/packages/state-hooks/tsconfig.json
monorepo/yarn.lock

- Rollup was not properly creating type declaration after build and declaration was containing absolute path like `src/xyz` which doesn't work in lib folder. To resolve the issue, we need to run `tsc-alias` after build which will fix all absolute path to relative path.
- But tsc-alias works only with same structure as src folder. that means it will not work if there are folders like `lib/cjs` & `lib/esm` so now we are just creating one folder `lib` and under that folder rollup will create `index.esm.js` and `index.cjs.js` file.

fix: shared & state-hooks build type declaration issue

---

src/state/pbridge/providers/rango.ts

This is a minor improvement for integrating Rango API for the bridge section. In this PR, I've added a check to prevent calling Rango API when blockchain or token symbol is not supported by Rango.

fix: avoid requesting rango api when blockchain/symbol is invalid
