pangolindex/components

- src/components/CurrencyInput/currencyInput.stories.tsx
- src/components/CurrencyLogo/index.tsx
- src/components/DoubleCurrencyLogo/doubleLogo.stories.tsx
- src/components/SwapWidget/MarketOrder/index.tsx
- src/components/SwapWidget/Settings/index.tsx
- src/components/SwapWidget/Settings/styled.ts
- src/constants/index.ts
- src/constants/lists.ts
- src/state/papplication/actions.ts
- src/state/puser/actions.ts
- src/state/puser/hooks.tsx
- src/state/puser/reducer.ts
- src/utils/index.ts
- Fix overflow with deadline
- Added checks for slippage tolerance, save button is disable case slippage tolerance is invalid
> Fix issues on swap widget settings

- src/components/SwapWidget/Settings/WarningModal.tsx
- src/components/SwapWidget/Settings/styled.ts
> Fix Warning Modal is not user friendly on mobile

- .eslintrc.js
- .gitignore
- package.json
- src/components/CheckboxGroup/CheckboxGroup.tsx
- src/components/CurrencyInput/CurrencyInput.tsx
- src/components/Logo/index.tsx
- src/components/Steps/Steps.tsx
- src/components/SwapWidget/ConfirmLimitOrderDrawer/index.tsx
- src/components/SwapWidget/LimitOrder/index.tsx
- src/hooks/useTransactionDeadline.ts
- src/state/papplication/actions.ts
- yarn.lock
> Prod: Moved sdk to peerDependancy & fix some sonar linting issue

- src/components/NewsWidget/NewsWidget.tsx
- src/components/NewsWidget/styleds.tsx
> fix NewsWidget

- src/components/Portfolio/Portifolio.tsx
- src/components/Portfolio/index.tsx
- src/components/Portfolio/portfolio.stories.tsx
- src/components/Portfolio/styleds.tsx
- src/components/SwapWidget/SelectTokenDrawer/index.tsx
- src/components/index.ts
- src/constants/index.ts
- src/state/pportifolio/hooks.ts
- Removed Avax from search list on SelectTokenDrawer
- [Added portfolio widget](https://github.com/pangolindex/components/commit/244a2b16b330790d23874bc4c8173e3ee48800bf)
> Update SelectTokenDrawer and add Portfolio widget

- src/components/WalletModal/PendingView/index.tsx
- src/components/WalletModal/index.tsx
- src/constants/index.ts
pre import all small icons & add it to iconName field instead of icon file name
> fix image import

- src/components/SwapWidget/MarketOrder/index.tsx
- src/constants/index.ts
- src/hooks/useSwapCallback.ts
- src/utils/near.ts
> solve token storage deposit issue

- src/index.tsx
Export ptransactions hooks and actions
> Export ptransactions hooks

- src/components/MyPortfolio/MyPortfolio.tsx
- src/components/MyPortfolio/PortfolioRow.tsx
- src/components/NewsWidget/styleds.tsx
- src/components/Portfolio/Portfolio.tsx
- src/components/Portfolio/styleds.tsx
- src/components/SwapWidget/LimitOrder/styled.tsx
- src/components/SwapWidget/MarketOrder/styled.tsx
- src/components/WatchList/CoinChart.tsx
- src/components/WatchList/CurrencyPopover/CurrencyRow.tsx
- src/components/WatchList/styleds.tsx
- src/state/pportfolio/hooks.ts
1. fix values show single digit cents
2. fix height of portoflio
3. Fixed some font size and font weight to conform to the design
> Fix design issues again and bugs on portfolio

- src/components/WalletModal/index.tsx
Fixed XDEFI show message "please install" with XDEFI wallet installed
This error happens when have just installed XDEFI and not was set a wallet
The user needs to refresh the page to be able to connect to XDEFI
> Fixed XDEFI show message "please install" 

- src/constants/index.ts
- src/state/pnews/hooks.ts
Updated news widget to new directus api and shows news according to connected chain
> Updated directus api and news widget

- src/components/SwapWidget/MarketOrder/index.tsx
- src/hooks/Trades.ts
- src/state/pswap/hooks.ts
> Added loading message on swap button

- src/hooks/useApproveCallback.ts
- Added wait confirmation on approve call back
> resolve delay on approve

- src/components/SwapWidget/index.tsx
- src/components/SwapWidget/swapWidget.stories.tsx
> Added swap widget option on story book

- package.json
- src/data/Reserves.ts
- src/utils/prices.ts
- yarn.lock
Include Near simple swap pairs and the ability to fetch filtered pair types (simple, stable, rated)
> Parse near pairs

- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/PoolCard/PoolCardV2.tsx
- src/components/Pools/PoolCard/PoolCardView.tsx
- src/components/Pools/PoolV2.tsx
- src/components/Pools/Stake/index.tsx
- src/state/pstake/hooks.ts
Change structure in a way that, When subgraph is down we can fallback to on chain data
> fallback to on chain minichef

- src/state/pstake/hooks.ts
- Fix claim issue
- fallback pool ids to on chain call
> fix claim issue

- src/components/Pools/AddLiquidity/index.tsx
- src/components/Pools/Remove/index.tsx
- src/components/Pools/RemoveFarm/index.tsx
- src/components/Pools/RemoveLiquidity/index.tsx
- src/components/Pools/Stake/index.tsx
- src/hooks/index.tsx
- src/state/pstake/hooks.ts
Refetch the minichef subgraph info to update all data from ui
this PR changes taken from https://github.com/pangolindex/interface/pull/571
> Refetch the minichef subgraph info to update all data from ui

- src/components/SarManageWidget/AddStake/index.tsx
- src/components/SarManageWidget/Claim/index.tsx
- src/components/SarManageWidget/Compound/RewardsInfo.tsx
- src/components/SarManageWidget/Compound/index.tsx
- src/components/SarManageWidget/ConfirmDrawer/index.tsx
- src/components/SarManageWidget/Title.tsx
- src/components/SarManageWidget/Unstake/index.tsx
- src/components/SarManageWidget/index.tsx
- src/components/SarManageWidget/types.ts
- src/components/SarNFTPortfolio/Portfolio.tsx
- src/components/SarNFTPortfolio/index.tsx
- src/components/SarStakeWidget/index.tsx
- src/index.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- Fixed `in wallet` png balance
- Fixed compound / claim widget not working property
- Fixed ConfirmDrawer items not centered
- Adjust items per page according page width and height
- Not show positions with balance 0 on portfolio widget
- Fixed overlay doesn't highlight Create a new position
- Export `existSarContract` to use on [interface](https://github.com/pangolindex/interface) 
- Fixed some translations
- Added position identifier to show selected position id
- Compound should show position dollar value and total average apr
> Fix SAR bugs

- src/components/Pools/AddLiquidityModal/index.tsx
Resolve issue for Create Pair Modal Crash for Avalanche Chain
> resolve create pair modal issue

- package.json
- src/constants/index.ts
- src/constants/multicall/index.ts
- src/state/psarstake/hooks.ts
- yarn.lock
Added coston sar stake
Added coston multicall
Fix division by zero on `useSarStakeInfo`
> Added coston sar stake

- src/connectors/index.ts
- src/constants/index.ts
- src/hooks/useWrapCallback.ts
- src/state/pwallet/hooks.ts
- src/utils/near.ts
1. Swap Wrap and unWrap
2. Add Liquidity with wNear
> add liquidity issue and wrap unwrap swap issue

- src/components/Pools/AddLiquidityModal/index.tsx
- src/components/Pools/PoolImportModal/PoolImport/index.tsx
- src/components/Pools/PoolImportModal/PositionCard/index.tsx
- src/index.tsx
- src/state/pburn/hooks.ts
- src/state/pmint/hooks.ts
- src/state/pstake/hooks.ts
- src/state/pswap/hooks.ts
- src/state/pwallet/hooks.ts
- src/utils/index.ts
Create Pool and Import (Find) Pool
> Near: Create pair/pool & Import Pool

- src/components/SwapWidget/LimitOrder/index.tsx
- src/components/SwapWidget/MarketOrder/index.tsx
- src/components/SwapWidget/TradeOption/index.tsx
- src/components/SwapWidget/index.tsx
- src/constants/index.ts
"SwapTypes" turned into an enum type.
onSwapTypeChange method added.
https://app.clickup.com/t/3buhjpx
> Added SwapTypes & SwapType Callback

- src/components/Pools/AddLiquidity/ConfirmPoolDrawer/index.tsx
- src/components/Pools/AddLiquidity/ConfirmPoolDrawer/styled.ts
https://app.clickup.com/t/3buhmd6
> Hid the deposit area on mobile

- src/components/Pools/PangoChef/Compound/index.tsx
- src/components/Pools/PangoChef/Compound/styleds.tsx
- src/components/Pools/PangoChef/Stake/ConfirmDrawer.tsx
- src/components/Pools/PangoChef/Stake/index.tsx
- src/components/Pools/PangoChef/Stake/styleds.tsx
- src/components/Pools/PoolCard/PoolCardV3.tsx
- src/components/Pools/PoolCard/PoolCardViewV3.tsx
- src/components/Pools/Remove/styleds.tsx
- src/components/Pools/RemoveFarm/index.tsx
- src/components/Pools/RemoveFarm/styleds.tsx
- src/components/Pools/Stake/index.tsx
- src/components/SarStakeWidget/index.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- Changed high volatility text to: **High volatility, try to compose later**
- Change the text **APR** to **Average APR** in v3 card
- Show user APR in v3 card
- Added remove warning and button to redirect to compound (just for pangochef ) in remove drawer
- Fixed png symbol on farm drawer to use chain png symbol
- Fixed **view on explorer** to open link in new tab
- Fixed balance text in farm drawer
- FIxed over buttons in farm drawer
- Fixed stepper/stake error not reset in stake drawer/detail
- Fixed sar stake new overflow
> Fix bugs, and issues with pangochef and sar stake

- src/hooks/useCurrencyPrice.ts
Fixed invariant issue when there is no liquidity it throws an error
> Fix invariant issue

- src/components/SwapWidget/SelectTokenDrawer/index.tsx
- src/components/WatchList/CurrencyPopover/index.tsx
- src/constants/index.ts
- src/hooks/Tokens.ts
- src/state/pportfolio/hooks.ts
- src/state/pswap/hooks.ts
- Swap Widget set default currency for Songbird
> fix: Swap Widget default currency for Songbird

- src/state/ppangoChef/hooks.ts
- Fixed array length
- Remove no erc20 pool from pangochef infos
> Fix farms not showing

- src/components/NetworkSelection/NetworkSelection.tsx
- src/components/Pools/DetailModal/Details/index.tsx
- src/components/Pools/PangoChef/Compound/index.tsx
- src/components/Pools/PangoChef/EarnDetail/index.tsx
- src/components/SarManageWidget/AddStake/index.tsx
- src/components/SarManageWidget/Claim/index.tsx
- src/components/SarManageWidget/Claim/styleds.tsx
- src/components/SarManageWidget/Compound/RewardsInfo.tsx
- src/components/SarManageWidget/Compound/index.tsx
- src/components/SarManageWidget/ConfirmDrawer/index.tsx
- src/components/SarNFTPortfolio/Portfolio.tsx
- src/components/SarNFTPortfolio/index.tsx
- src/components/SarStakeWidget/index.tsx
- src/constants/index.ts
- src/constants/tokens.ts
- src/hooks/Tokens.ts
- src/hooks/multiChainsHooks.ts
- src/hooks/useCurrencyPrice.ts
- src/hooks/useUSDCPrice.ts
- src/locales/en.json
- src/state/ppangoChef/hooks.ts
- src/state/psarstake/hooks.ts
- src/utils/index.ts
- Added songbird usd token price
- Added total staked in wavax and usd in pangochef infos
- Fixed your liquidity in usd to use user pgl
- Fixed view explorer to open in new tab
- Fixed page number incorrect after sorting
- Fixed compound warning 
- Sort stakev2 positions by balance by default
- Fixed useSarPositions to get data automatically
> Fix SAR bugs & implement usd price for Songbird chain

- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/PangoChef/Compound/index.tsx
- src/components/Pools/PangoChef/EarnDetail/index.tsx
- src/components/Pools/PangoChef/Stake/index.tsx
- src/components/Pools/Remove/index.tsx
- src/components/Pools/RemoveDrawer/index.tsx
- src/components/Pools/RemoveFarm/index.tsx
- src/components/SarNFTPortfolio/Portfolio.tsx
- src/components/SarStakeWidget/index.tsx
- src/components/SarStakeWidget/styleds.tsx
- src/connectors/WalletProviders/CommonEVMProvider.ts
- src/connectors/WalletProviders/NearProvider.ts
- src/constants/index.ts
- src/hooks/index.tsx
- src/react-app-env.d.ts
- src/state/ppangoChef/hooks.ts
- Fix useGetBlockTimestamp
- Fixed `your apr ` appears without stake
- Fixed page number not updating correctly 
- Fixed `Stake new sar widget` overflow
- Fixed farm stepper
- Fix redirect to compound
- Adeed png symbol in pangochef earned widget 
- Fix compound issues (changed slippage from 1% to 2%)
> Fix Sar bugs 2

- src/state/pswap/reducer.ts
Fix Issue for Currency Switch in Swap
> fix switch currency issue

- .github/workflows/build-artifacts.yml
- .github/workflows/publish-alpha.yml
- .github/workflows/publish-beta.yml
- package.json
This is WIP progress PR but merging it so that publish-alpha.yml will be available in dev.
> fix: npm alpha build

- README.md
> THROWAWAY PR

- .github/workflows/commitlint.yml
- .husky/commit-msg
- commitlint.config.js
- package.json
- yarn.lock
This PR add changes for linting commits.
- added commit hook to check commits
- add github action to lint messages
> feat: add commitlint

- src/components/Pools/AddLiquidityModal/SearchToken.tsx
- src/components/Pools/PoolImportModal/PoolImport/index.tsx
- src/components/Pools/PoolImportModal/PoolImport/styleds.tsx
- src/components/Pools/PoolList/PoolListV3.tsx
- src/components/SwapWidget/LimitOrder/index.tsx
- src/components/SwapWidget/SelectTokenDrawer/CurrencyGrid.tsx
- src/components/SwapWidget/SelectTokenDrawer/index.tsx
- src/components/SwapWidget/SelectTokenDrawer/styled.ts
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- src/utils/index.ts
- Fixed some translations
- Fixed limit order does not appear transaction complete popup
- Redesign select token drawer
- Added description for import pool, create pair and add liquidity in modal
> Fix some bugs

- src/components/SwapWidget/MarketOrder/index.tsx
- src/hooks/Tokens.ts
- src/hooks/useSwapCallback.ts
- src/state/pswap/hooks.ts
- src/utils/hedera.ts
- src/utils/index.ts
1. When Enable Expert mode Transfer Currency to another wallet address 
2. For Hedera  its solved  based on recipient
> fix: hedera swap expert mode

- src/components/Pools/Stake/index.tsx
- fixed minicheft pools stepper not updating automatically
> fix: minicheft pools stepper

- src/state/ppangoChef/hooks.ts
Fixed  bigNumber underflow in useUserPangoChefAPR
> fix: big number underflow in useUserPangoChefAPR

- src/components/MyPortfolio/MyPortfolio.tsx
- src/components/Portfolio/Portfolio.tsx
- src/constants/index.ts
- src/state/pportfolio/hooks.ts
- src/state/puser/actions.ts
- src/state/puser/hooks.tsx
- src/state/puser/reducer.ts
- Fixed portfolio infinity loading
- Added redux actions to show balances
> fix: portfolio bugs

- src/state/pstake/hooks.ts
- fix: extra earned tokens rewards not showing in avalanche
this happens because the `miniChefStaking?.earnedAmount` exists in the avalanche and is 0 making the calculation always be 0, to resolve this we will always use the highest earned amount value between `miniChefStaking?.earnedAmount` and `_earnedAmount`
> fix: extra earned tokens rewards not showing in avalanche

- src/assets/images/hedera.svg
- src/components/CurrencyLogo/index.tsx
- src/components/Pools/PangoChef/ClaimReward/index.tsx
- src/components/Pools/RemoveFarm/index.tsx
- src/state/ppangoChef/hooks.ts
- src/state/ppangoChef/multiChainsHooks.ts
- src/utils/hedera.ts
1. Claim Process 
2. Withdraw Process
> feat: hedera pangochef withdraw & claim

- src/components/SwapWidget/SelectTokenDrawer/index.tsx
- src/hooks/Tokens.ts
- src/utils/hedera.ts
- fix: white screen issue
- fix: create pair issue by increasing payable amount
- fix: rendering key issue in grid
> fix: few hedera bugs

- src/utils/hedera.ts
- src/utils/index.ts
- swap expert mode recipient Issue
> fix: swap expert mode recipient validation issue

- package.json
- src/components/SwapWidget/MarketOrder/index.tsx
- src/state/pswap/hooks.ts
- src/utils/hedera.ts
- src/utils/index.ts
- yarn.lock
- Receipient Address Validation Issue
> fix: swap receipient address validation issue

- src/components/SarManageWidget/Unstake/index.tsx
- src/components/SarStakeWidget/index.tsx
- src/hooks/Tokens.ts
- src/state/pmulticall/hooks.ts
- src/state/psarstake/dummyHooks.ts
- src/state/psarstake/hederaHooks.ts
- src/state/psarstake/hooks.ts
- src/state/psarstake/multiChainsHooks.ts
- src/state/psarstake/utils.ts
- src/utils/hedera.ts
- Fixed to use dynamically hbar amount to pay the rent
- Added pagination to get hedera nfts
- Fixed format units according to png decimals
- Added Hedera Unstake
> fix: hedera sar listing & unstake

- src/components/SarManageWidget/Claim/index.tsx
- src/components/SarManageWidget/Compound/index.tsx
- src/state/psarstake/dummyHooks.ts
- src/state/psarstake/hederaHooks.ts
- src/state/psarstake/hooks.ts
- src/state/psarstake/multiChainsHooks.ts
- src/state/psarstake/utils.ts
- src/utils/hedera.ts
- Fixed the png decimals in frontend
- Added sar compound and claim for hedera
> fix: hedera sar compound & claim

- src/components/Pools/index.tsx
- src/hooks/useCurrencyPrice.ts
- src/state/ppangoChef/hooks.ts
> fix: hedera farms apr issue

- src/constants/tokens.ts
- src/hooks/multiChainsHooks.ts
- src/hooks/useUSDCPrice.ts
- src/state/ppangoChef/hooks.ts
- add `useHederaUSDPrice` hook to get hedera tokens price in usd
> fix: hedera usdc value hook

- package.json
- src/components/Pools/DetailModal/DetailView/index.tsx
- src/components/Pools/DetailModal/Details/index.tsx
- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/DetailModal/index.tsx
- src/components/Pools/PangoChef/Compound/index.tsx
- src/components/Pools/PangoChef/Stake/index.tsx
- src/components/Pools/PoolCard/PoolCardV3.tsx
- src/components/Pools/PoolCard/PoolCardViewV3.tsx
- src/components/Pools/PoolList/PoolListV3.tsx
- src/hooks/useApproveCallback.ts
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- src/state/papplication/actions.ts
- src/state/papplication/hooks.ts
- src/state/papplication/reducer.ts
- src/state/ppangoChef/hooks.ts
- src/utils/hedera.ts
- yarn.lock
1. Compound Integration
2. After Create Pangochef storage  Detail Modal Issue
> fix: compound and create storage issue resolved

- package.json
- yarn.lock
> fix: update hashgraph sdk version

- src/components/NewsWidget/styleds.tsx
- src/components/Portfolio/Portfolio.tsx
- src/components/Portfolio/styleds.tsx
> fix: portfolio and news widget ui changes

- example/package.json
- example/src/layout/Logo/styled.ts
- example/src/layout/styled.ts
- example/yarn.lock
- package.json
- src/components/Pools/PangoChef/EarnDetail/index.tsx
- src/constants/abis/pangochef.json
- src/state/ppangoChef/hooks.ts
- src/state/ppangoChef/multiChainsHooks.ts
- src/state/ppangoChef/types.ts
- src/utils/hedera.ts
- yarn.lock
1.  lockCount Condition Changes 
2. compoundTo method
> fix: update for compound and lockcount

- src/components/Pools/Sidebar/index.tsx
- src/components/Pools/Sidebar/styleds.tsx
- src/components/Pools/index.tsx
- src/components/Pools/styleds.tsx
Change Place For Create Pair  make Full grid view for pool
> fix: change create pair button place

- src/state/ppangoChef/hooks.ts
- Fixed pangochef white screen issue
> fix: pangochef white screen

- example/package.json
- example/src/main.tsx
- example/yarn.lock
- src/components/Pools/PangoChef/EarnDetail/index.tsx
- src/hooks/useContract.ts
- Fixed the withdraw issue, this happnes because the UI don't show correctly the locking farms, then the use able to click in remove not being able to click
- Now in example app it try to active the wallet only in mobile
> fix: locking to farm issue

- example/package.json
- example/src/main.tsx
- example/yarn.lock
- src/components/Pools/PangoChef/EarnDetail/index.tsx
- src/hooks/useContract.ts
> prod: fix: locking to farm issue

- src/components/Pools/PangoChef/EarnDetail/index.tsx
- src/state/ppangoChef/hooks.ts
- Fixed the farms diferente of 0 locked in songbird
> fix: songbird locking pools other than 0

- src/state/ppangoChef/hooks.ts
- Fixed compound issue not is poossible the pools with id greather then 9
> fix: compound issue

- src/components/Pools/RemoveLiquidity/index.tsx
- src/components/SwapWidget/MarketOrder/index.tsx
- src/hooks/useWrapCallback.ts
- add loading text when user do wrap/unwrap
- add close button in remove liquidity
- https://app.clickup.com/t/8669axmud
- https://app.clickup.com/t/8669axuqr
> fix: hedera ui bugs

- src/components/CurrencyLogo/index.tsx
- src/components/DoubleCurrencyLogo/DoubleCurrencyLogo.tsx
- src/components/DoubleCurrencyLogo/styles.tsx
- Fixed the double currency bug
> fix: double currency logo

- example/src/App.tsx
- example/src/layout/Header/index.tsx
- example/src/pages/SarSingleStake/index.tsx
- example/src/pages/SarSingleStake/styled.ts
- src/components/SarManageWidget/AddStake/index.tsx
- src/components/SarManageWidget/Claim/index.tsx
- src/components/SarManageWidget/Compound/index.tsx
- src/components/SarManageWidget/Unstake/index.tsx
- src/components/SarNFTPortfolio/index.tsx
- src/components/SarStakeWidget/index.tsx
- src/state/psarstake/hederaHooks.ts
- Fixed portfolio in Hedera Sar not updating
- Added Sar page in example app
- Close drawer when select another position
- Decrease cache time in exchange rate query
- Unselect position when remove all from one
> fix: bugs in hedera sar

- src/connectors/HashConnector/index.ts
- src/constants/index.ts
- src/state/pwallet/hooks.ts
- src/utils/hedera.ts
- move hedera base url to hedera utils
- choose client & base url dynamically based on chain id
> fix: hedera mainnet/testnet configuration

- src/connectors/index.ts
this approach is for short term only
once we have new wallet modal ready
we will need to replace this with more elegant approach
> fix: handle hedera network using localstorage temp

- src/state/pmulticall/updater.tsx
- src/state/ppangoChef/hooks.ts
Hedera mainnet Pool Blink Issue 
multicall chunksize greater than 30 is not working in hedera so its reduced to 30
> fix: hedera mainnet pool blink issue resolved

- src/components/SarManageWidget/AddStake/index.tsx
- src/components/SarStakeWidget/index.tsx
- Hedera has new hook for token balance, we need to update this to using according with chain
> fix: sar to use multichain token balance hook

- src/components/SarManageWidget/Compound/index.tsx
- Fixed dollar price causing white screen when click in compound
> fix: dollar price white screen issue

- src/state/psarstake/hederaHooks.ts
- src/state/psarstake/utils.ts
- Fixed dollar price division by 0 issue
> fix: dollar price division by 0 issue

- src/hooks/useContract.ts
- Fixed the white screen issue in stake page, it is cause by the useHederaSarNFTContract converting a nonexistent address to hedera address
> fix: white screen issue in stake page

- src/apollo/client.ts
- src/apollo/pairs.ts
- src/apollo/tokens.ts
- src/components/Pools/PangoChef/Compound/index.tsx
- src/hooks/multiChainsHooks.ts
- src/hooks/useCurrencyPrice.ts
- src/hooks/useUSDCPrice.ts
- src/state/pmulticall/updater.tsx
- src/state/ppangoChef/hooks.ts
- src/state/pstake/hooks.ts
> fix: hedera farm apr & tvl

- src/apollo/tokens.ts
- src/components/SwapWidget/MarketOrder/index.tsx
- src/hooks/useCurrencyPrice.ts
- src/state/pswap/hooks.ts
- src/utils/hedera.ts
- src/utils/index.ts
this commit fixes issues happening due to lowercase subgraph token addresses subgraph has lowercase token id so when we send addresses to subgraph in request we need to pass lowercase address but when we get response from subgraph we need to convert lowercase address to checksum address to make it consistent with entire codebase
> fix: lowercase subgraph address issue

- src/connectors/HashConnector/index.ts
> fix: try - hashpack install issue resolve

- src/components/SwapWidget/MarketOrder/index.tsx
> fix: add space after swap approve button

- src/components/Portfolio/Portfolio.tsx
> fix: typo in portfolio component

- example/src/layout/Header/index.tsx
- example/src/layout/Header/styled.ts
- src/hooks/useUSDCPrice.ts
- src/index.tsx
this PR fixes useUsdPriceCoingecko where we needed to pass values in terms of base & quote currency decimals always so it will raw values properly when base & quote currency decimals are different
> fix: pbar(any token) price via usdc hook

- src/hooks/bridge/Chains.ts
The Evmos chain is defined as the EVM chain on the Rango side, and as Cosmos Chain on the Squid side. This PR removes it from the Squid side and accepts the Rango side. 
This is not the best solution. Need to think about the solution for the future.
> fix: evmos chain conflict in bridge

- src/hooks/Tokens.ts
- fix: hedera Your Pools list bug
> fix: hedera your pool list bug resolved

- src/hooks/useApproveCallback.ts
- src/state/puser/actions.ts
- src/state/puser/hooks.tsx
- src/state/puser/reducer.ts
- Added in redux, in user config if user allow to approve infinite amount
- For hedera we need to approve infinite, we use the `token.totalSupply`
> feat: added redux on user config to approve infinite

- src/state/pbridge/providers/squid.ts
This PR fixes the wrong fee of 0xSquid Routes.
> fix: 0xsquid fee

- example/src/layout/Header/index.tsx
- src/components/SwapWidget/MarketOrder/index.tsx
- src/index.tsx
- src/utils/index.ts
1. Percentage Reset on  Switch Currency and After swap done 
2. Show Hedera Account id instead of address
> fix: swap percentage issue and hedera account id show instead of address

- src/utils/hedera.ts
- fix: increasing hedera farm staking gas
> fix: increasing hedera farm staking gas

- src/state/ppangoChef/hooks.ts
- fix: hedera superfarm apr
- in Superfarm extra APR we need to divide by 10^8 specifically for Hedera to solve decimal related issue
> fix: hedera superfarm apr

- src/connectors/HashConnector/index.ts
fix: Multiple approve popup in hedera dApp
> fix: multiple approve popup in hedera dapp

- src/apollo/tokens.ts
- src/state/plists/hooks.ts
- src/state/ppangoChef/hooks.ts
- src/state/pstake/hooks.ts
- fix: infinite rendering issue in detail modal
> fix: infinite rendering issue in detail modal

- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/PoolCard/PoolCardViewV3.tsx
- src/state/ppangoChef/hooks.ts
- Fixed the decimals issue with apr calculation
- Fixed the extra apr to use staked amount and total staked amount to calculate this more fast
> fix: hedera farms aprs

- src/data/TotalSupply.ts
- src/data/multiChainsHooks.ts
- src/hooks/useApproveCallback.ts
- src/utils/hedera.ts
Replace total supply ETH_Call to API Call
> fix: remove eth call for totalsupply use api

- src/components/Pools/AddLiquidity/ConfirmPoolDrawer/index.tsx
- src/components/Pools/AddLiquidityModal/SearchToken.tsx
- src/components/Pools/PangoChef/Compound/index.tsx
- src/components/Pools/PangoChef/Stake/ConfirmDrawer.tsx
- src/components/Pools/PangoChef/Stake/index.tsx
- src/components/Pools/Stake/index.tsx
- src/hooks/useApproveCallback.ts
- src/locales/en.json
- src/state/pwallet/hooks.ts
https://app.clickup.com/t/8669j32fe
https://app.clickup.com/t/8669j32f7
https://app.clickup.com/t/8669hj13d
https://app.clickup.com/t/8669j32g3
https://app.clickup.com/t/8669g427w
https://app.clickup.com/t/8669hj0wn
> fix: hedera bug fixes

- src/constants/index.ts
- Change default destination token in Swap to PBAR
> fix: change default output currency on hedera to pbar

- src/index.tsx
- src/state/pswap/multiChainsHooks.ts
- add some extra export for interface
> fix: add some extra export for interface

- src/components/Box/Box.tsx
- remove default black color for box component
> fix: remove default box color

- src/components/NewsWidget/styleds.tsx
> fix: news widget color

- example/package.json
- example/yarn.lock
- package.json
- src/apollo/block.ts
- src/apollo/client.ts
- src/apollo/pairs.ts
- src/apollo/pangochef.ts
- src/apollo/tokens.ts
- src/components/Pools/PoolCard/styleds.tsx
- src/constants/index.ts
- src/state/pstake/hooks.ts
- src/state/ptoken/hooks.ts
- yarn.lock
> fix: make subgraph url chain wise

- src/components/Pools/DetailModal/DetailView/styleds.tsx
- src/components/Pools/DetailModal/Header/styled.tsx
- src/components/Pools/PoolCard/styleds.tsx
Light Mode
1. Pool Detail Modal Border
2. Pool Card Border
> fix: detail view border changes

- src/components/SwapWidget/Settings/index.tsx
> feat: hot fix slippage for hedera

- package.json
- src/components/NetworkSelection/index.tsx
- src/components/SwapWidget/Settings/index.tsx
- src/hooks/index.tsx
-  removed autconnect to hashpack
- reverted slippage changes
> feat: removed hedera 

- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/PoolCard/PoolCardViewV3.tsx
- src/state/ppangoChef/hooks/common.ts
- Fix apr issue in songbird/flare
> fix: songbird/flare apr bug

- src/index.tsx
- src/state/index.ts
- this is considered as a breaking change as we have migrated all redux state to jotai and removed pangolin redux store
> fix!: remove react redux store

- src/components/Modal/index.tsx
- src/components/Pools/DetailModal/DetailView/styleds.tsx
- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/DetailModal/Header/styled.tsx
- src/components/Pools/DetailModal/StatDetail/styleds.tsx
- Fix Tablet View for Pool/Farm Detail Modal
> fix: tablet view for farm detail modal

- src/components/Modal/index.tsx
- src/components/Pools/DetailModal/DetailView/styleds.tsx
- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/DetailModal/Header/styled.tsx
- src/components/Pools/DetailModal/StatDetail/styleds.tsx
- src/components/Pools/PangoChef/ClaimReward/index.tsx
- src/components/Pools/RemoveFarm/index.tsx
> fix: hotfixes to prod

- src/components/Pools/DetailModal/Details/index.tsx
- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/Pool/PoolV2.tsx
- src/components/Pools/Pool/PoolV3.tsx
- src/components/Pools/PoolCard/PoolCardView.tsx
- src/components/Pools/PoolCard/PoolCardViewV3.tsx
- src/components/Pools/index.tsx
- src/state/ppangoChef/hooks/common.ts
- src/state/ppangoChef/hooks/evm.ts
- src/state/pstake/hooks/evm.ts
- Fix extra apr issue
- Fix Minichef superfarms
- Fix Minichef claim
> fix: bugs related to extraAPR & superfarm in minichef & pangochef

- package.json
- src/components/ConcentratedLiquidity/index.tsx
- src/constants/address.ts
- src/constants/concentratedLiquidity/abis/nonfungiblePositionManager.json
- src/hooks/useContract.ts
- src/state/pwallet/concentratedLiquidity/hooks/dummy.ts
- src/state/pwallet/concentratedLiquidity/hooks/evm.ts
- src/state/pwallet/concentratedLiquidity/hooks/index.ts
- src/state/pwallet/concentratedLiquidity/types.ts
- yarn.lock
- NFT Positions Manager
- Listing Positions Hooks
> feat: concentrated liquidity positions

- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
- updated sdk to fix compound issue
> chore: updated sdk

- example/package.json
- example/yarn.lock
- package.json
- src/components/ConcentratedLiquidity/AddLiquidity/PriceRange/PriceInput/types.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/PriceRange/index.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/PriceRange/types.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/SelectPair/index.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/SelectPair/types.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/index.tsx
- src/constants/abis/IPangolinV2PoolState.json
- src/constants/abis/concentratedPool.ts
- src/hooks/concentratedLiquidity/hooks.ts
- src/state/pmint/concentratedLiquidity/atom.ts
- src/state/pmint/concentratedLiquidity/hooks.ts
- src/state/pmint/concentratedLiquidity/utils.ts
- yarn.lock
- add concentrated liquidity atom
- Hooks defined
- useDerivedMintInfo
- useMintActionHandlers
- useMintState
- usePools
- usePool
- ABIs added
- IPangolinV2PoolState.json
> feat(wip): concetrated add liquidity

- src/components/ConcentratedLiquidity/PositionList/index.tsx
- src/components/ConcentratedLiquidity/PositionList/styles.tsx
- src/components/ConcentratedLiquidity/index.tsx
- src/components/ConcentratedLiquidity/styles.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- src/state/pwallet/concentratedLiquidity/types.ts
It includes Con Liq "Listing Positions"
-> Sort by
-> Menu
-> Search
Actions.
> feat: sortby&search&menu actions added

- src/state/ppangoChef/hooks/index.ts
- change farms loading from subgraph to on chain
> feat: change subgraph to onchain

- src/apollo/client.ts
- src/state/ppangoChef/hooks/index.ts
> fix: replace hedera subgraph url

- src/apollo/client.ts
- replace hedera to main subgraph
> fix: revert hedera shubgraph url to main subgraph

- example/package.json
- example/yarn.lock
- package.json
- src/components/ConcentratedLiquidity/DetailModal/EarnWidget/Remove/index.tsx
- src/components/ConcentratedLiquidity/DetailModal/EarnWidget/Remove/types.tsx
- src/components/ConcentratedLiquidity/DetailModal/EarnWidget/RemoveDrawer/index.tsx
- src/components/ConcentratedLiquidity/DetailModal/EarnWidget/RemoveDrawer/removeDrawer.stories.tsx
- src/components/ConcentratedLiquidity/DetailModal/EarnWidget/index.tsx
- src/components/ConcentratedLiquidity/DetailModal/index.tsx
- src/components/ConcentratedLiquidity/DetailModal/styles.tsx
- src/components/ConcentratedLiquidity/PositionCard/index.tsx
- src/hooks/concentratedLiquidity/hooks/evm.ts
- src/state/pburn/concentratedLiquidity/common.ts
- src/state/pburn/concentratedLiquidity/evm.ts
- src/state/pburn/concentratedLiquidity/index.ts
- src/state/pburn/types.ts
- src/state/pwallet/concentratedLiquidity/hooks/evm.ts
- src/state/pwallet/concentratedLiquidity/hooks/index.ts
- src/state/pwallet/concentratedLiquidity/types.ts
- yarn.lock
Conc Liq
=> Earn - Collect Fees Function
=> Remove Liquidity
> feat(concetrated-liq): collect fees ( claim ) & remove liq

- src/components/Pools/AddLiquidity/ConfirmPoolDrawer/index.tsx
- src/components/Pools/DetailModal/Header/index.tsx
- src/components/Pools/PangoChef/Compound/index.tsx
- src/components/Pools/PangoChef/EarnDetail/index.tsx
- src/components/Pools/Pool/mock.ts
- src/components/Pools/PoolCard/PoolCardViewV3.tsx
- src/components/Pools/PoolList/PoolListV3.tsx
- src/components/Pools/RemoveFarm/index.tsx
- src/components/Pools/Stake/index.tsx
- src/constants/index.ts
- src/hooks/useCurrencyPrice.ts
- src/state/pburn/hooks.ts
- src/state/ppangoChef/hooks/common.ts
- src/state/ppangoChef/hooks/evm.ts
- src/state/ppangoChef/hooks/hedera.ts
- src/state/ppangoChef/types.ts
- src/state/ppangoChef/utils.ts
- Fixed Insufficient PGL balance
- Fixed PGL showing NaN
- Fixed compound button text color issue
- Fixed earned widget collapsing
- Disabled the staking widget fields if user don't have pgl
- Fixed apr decimals
- Fixed pair price  causing blank screen
- Fix sortby farms in farms version 3
- https://app.clickup.com/t/8669wfw79
- https://app.clickup.com/t/8669wf5m9
- https://app.clickup.com/t/8669vde2c
- https://app.clickup.com/t/8669wg4aw
- https://app.clickup.com/t/8669b9vu0
> fix: various ui bugs

- example/package.json
- example/src/utils/theme.ts
- example/yarn.lock
- package.json
- src/apollo/feeTierDistribution.ts
- src/components/ConcentratedLiquidity/AddLiquidity/ConfirmDrawer/index.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/PriceRange/PriceInput/index.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/SelectPair/index.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/SelectPair/styles.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/SelectPair/types.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/addLiquidity.stories.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/index.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/types.tsx
- src/components/ConcentratedLiquidity/DetailModal/EarnWidget/index.tsx
- src/components/ConcentratedLiquidity/DetailModal/Header/index.tsx
- src/components/ConcentratedLiquidity/DetailModal/Tabs/DetailTab/index.tsx
- src/components/ConcentratedLiquidity/PositionCard/index.tsx
- src/components/ConcentratedLiquidity/PositionCard/types.tsx
- src/components/ConcentratedLiquidity/index.tsx
- src/components/Modal/index.tsx
- src/hooks/concentratedLiquidity/hooks/evm.ts
- src/hooks/useEscapeKey.tsx
- src/state/pmint/concentratedLiquidity/atom.ts
- src/state/pmint/concentratedLiquidity/hooks.ts
- yarn.lock
1. Confirm Screen Data Correction 
2. Price Range Currency Name display 
3. 1 baseCurrency  =  Quote Currency 
4. Modal Close on Esc key
5.  Toggle Currency 
6. Currency AVAX Display issue
> fix: concentrated add liquidity bug

- example/src/pages/Swap/index.tsx
- src/components/SwapWidget/MarketOrder/index.tsx
- Fixed to change currency in swap to change in limit
- Show limit order in example app
> fix: bugs related to swap limit token selection

- src/components/Pools/AddLiquidity/ConfirmPoolDrawer/index.tsx
- src/components/Pools/PoolCard/PoolCardViewV3.tsx
- src/components/SarManageWidget/AddStake/index.tsx
- Fixed field "Share of pool" collapsing
- Fixed compound button on PoolCard to appears if the farm multiplier is greater than 0
- Fixed the "associate" button appears for few milliseconds on sar stake manage
> fix: bugs related to SAR NFT address, compound & display value

- package.json
- src/connectors/HashConnector/index.ts
- yarn.lock
- This fix update the hashgraph sdk to able to change the node when it fail, we need to make this to this the error bellow
- The fix was proposed by the hashpack team and you can see it below
[Gravação de tela de 21-04-2023 09:18:55.webm](https://user-images.githubusercontent.com/37405304/233646695-2c3a7035-6943-4fd5-a8df-bf2e1841f76d.webm)
> fix: update hedera sdk to fix transactions issue

- src/components/ConcentratedLiquidity/AddLiquidity/ConfirmDrawer/index.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/index.tsx
1. Add liquidity loading change
> fix: conc liq loading message change

- package.json
- src/components/WalletModal/index.tsx
- yarn.lock
- update walletconnect to fix connection issue
> fix: update walletconnect package

- src/state/pmint/concentratedLiquidity/hooks.ts
For new concentrated pool, fetch pair price from v2 pool so user will have initial price
> fix: set initial starting price automatically

- src/components/SwapWidget/ConfirmLimitOrderDrawer/index.tsx
- src/components/SwapWidget/LimitOrder/index.tsx
- src/components/SwapWidget/LimitOrderDetailInfo/index.tsx
- src/components/SwapWidget/MarketOrder/index.tsx
- src/state/pswap/atom.ts
- src/state/pswap/hooks/index.ts
- useGelatoLimitOrders provided by `@gelatonetwork` need a caution because this doesn't work in hedera because it doesn't have gelato in this one
> fix: gelato crash in swap widget on hedera

- src/components/Pools/DetailModal/EarnedDetail/styleds.tsx
- src/components/Pools/PangoChef/EarnDetail/styleds.tsx
- src/components/SarManageWidget/AddStake/index.tsx
- Fixed earned widget cut off
- https://app.clickup.com/t/866a44u7a
> fix: earned widget cut off

- example/package.json
- example/yarn.lock
- package.json
- src/apollo/elixirPools.ts
- src/components/ConcentratedLiquidity/DetailModal/EarnWidget/Remove/index.tsx
- src/components/ConcentratedLiquidity/DetailModal/Tabs/DetailTab/index.tsx
- src/components/SelectChainDrawer/index.tsx
- src/components/SwapWidget/ConfirmSwapDrawer/index.tsx
- src/components/SwapWidget/MarketOrder/index.tsx
- src/components/SwapWidget/SwapDetailInfo/index.tsx
- src/components/SwapWidget/SwapRoute/index.tsx
- src/hooks/Trades.ts
- src/hooks/bridge/Currencies.ts
- src/hooks/concentratedLiquidity/hooks/evm.ts
- src/hooks/concentratedLiquidity/hooks/index.ts
- src/hooks/useApproveCallback/evm.ts
- src/hooks/useSwapCallback/evm.ts
- src/state/pbridge/providers/rango.ts
- src/state/pswap/hooks/common.ts
- src/utils/index.ts
- src/utils/prices.ts
- yarn.lock
- SDK ChainId Changes
- Hooks added
- useAllConcentratedCommonPools
- useConcentratedTradeExactIn
- useConcentratedTradeExactOut
- updated useSwapCallback to support elixir routing
> feat: implement elixir routing in swap

- src/components/ConcentratedLiquidity/AddLiquidity/PriceRange/index.tsx
- src/components/ConcentratedLiquidity/AddLiquidity/index.tsx
- src/components/ConcentratedLiquidity/PositionCard/index.tsx
- src/components/ConcentratedLiquidity/PositionList/index.tsx
- src/components/ConcentratedLiquidity/PositionList/styles.tsx
- src/components/ConcentratedLiquidity/Sidebar/index.tsx
- src/components/ConcentratedLiquidity/index.tsx
- src/components/ConcentratedLiquidity/styles.tsx
- src/components/LiquidityChartRangeInput/index.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- src/state/pmint/concentratedLiquidity/hooks.ts
- The user can see the menu on the mobile device if he doesn't have any (Opened/Closed) position.
- AVAX/WAVAX => shouldn't be selectable in "Add Liquidity".
- Changed the `Go to Farm` link.
- Added Tooltips
- Removed `FullRange` button
> fix: closed position issue & code refactoring

- src/components/Elixir/AddLiquidity/PriceRange/index.tsx
- src/components/Elixir/AddLiquidity/PriceRange/types.tsx
- src/components/Elixir/AddLiquidity/index.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- Full Range icon(button) added.
> fix(elixir): full range button

- src/state/pswap/hooks/common.ts
- Fix infinite loading message in swap widget
> fix: loading message in swap widget

- src/components/Elixir/AddLiquidity/index.tsx
- src/components/Elixir/AddLiquidity/styles.tsx
> fix: elixir add liq mobile scroll issue

- src/state/ppangoChef/hooks/evm.ts
- src/state/ppangoChef/hooks/hedera.ts
- src/state/ppangoChef/utils.ts
- Changed the `calculateUserRewardRate` function to use BigNumber again, to approach with values calculate on chain
> fix: reward rate to use bignumber to approach to on chain

- src/components/Elixir/Sidebar/index.tsx
- Fix the standard pool redirection bug 
https://app.clickup.com/t/866a6zv8d
> fix: standard pool redirection bug from Elixir

- example/package.json
- example/yarn.lock
- package.json
- src/apollo/client.ts
- src/apollo/singleStake.ts
- src/state/psarstake/hooks/evm.ts
- src/state/psarstake/hooks/hedera.ts
- src/state/psarstake/utils.ts
- yarn.lock
- fetch sar nfts from subgraph
- https://app.clickup.com/t/864em26r1
- https://github.com/pangolindex/sdk/pull/137
> fix: fetch sar nfts from subgraph

- src/state/psarstake/hooks/evm.ts
- src/state/psarstake/hooks/hedera.ts
- Fixed position show wrong id, this a sort issue because subgraph return the positions order by id (0x1, 0x10, 0x2, 0x3...) and and it makes the frontend not get a wrong position in the array because the indexes are right (0x1, 0x2, 0x3, 0x10,...)
> fix: sort position issue

- src/components/Elixir/AddLiquidity/PriceRange/PriceInput/index.tsx
- src/components/Elixir/AddLiquidity/index.tsx
- src/components/Modal/index.tsx
1 - Fixed `Set Price Start` 0 input issue.
2- Fixed Infinity Character Issue
3- Fixed Connect Wallet Modal Visibility issue
1 - https://sharing.clickup.com/36619926/t/h/866a6zuzm/D9ZV83TJT3KS19H
2- https://sharing.clickup.com/36619926/t/h/866a6u62z/D9ZV83TJT3KS19H
3- https://sharing.clickup.com/36619926/t/h/866a6zv2m/D9ZV83TJT3KS19H
> fix: elixir issues

- src/state/pmulticall/updater.tsx
- Decreased hedera multicall chunk size (this not fix rate limit issue)
> fix: decreased hedera multicall chunk size

- src/components/Elixir/AddLiquidity/index.tsx
- src/components/Elixir/index.tsx
- src/components/Elixir/styles.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- src/state/pmint/elixir/hooks.ts
- Added "Go to Farm Page" on mobile
- https://app.clickup.com/t/866a6zw80
> fix(mobile): display classic farm link in elixir

- src/components/Pools/AddLiquidity/ConfirmPoolDrawer/index.tsx
- Fixed NaN and undefined in pgl
- https://app.clickup.com/t/8669wf5m9
> fix: NaN and undefined in pgl

- src/components/Bridge/bridge.stories.tsx
- src/state/pmint/elixir/hooks.ts
- An issue arose with the V2 Price in Elixir, wherein the page would break when the V2 Price was set to 0. To address this, I implemented a conditional statement to handle this particular scenario and prevent any further disruptions.
- Updated Bridge storybook description.
- https://app.clickup.com/t/866a8cny1
> fix: elixir v2 price bug

- src/components/Bridge/BridgeInputsWidget/index.tsx
- src/components/Bridge/BridgeInputsWidget/styles.tsx
- src/components/Bridge/BridgeRoute/index.tsx
- src/components/ChainInput/styles.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- Bridge Inputs were causing issues with the user interface, resulting in a broken UI. As a solution, the input styles have been modified.
- The overflowed text has been adjusted for mobile devices to ensure proper display.
- https://app.clickup.com/t/388815r
- https://app.clickup.com/t/3888194
> fix: bridge bugs

- src/components/Pools/PoolCard/PoolCardViewV3.tsx
- src/components/Pools/PoolCard/styleds.tsx
- Add Expire Tage for Expired Pool
Clickup : https://app.clickup.com/t/866a9qj3j
> fix: add expire tag for weight 0 pool

- src/state/pmint/elixir/hooks.ts
- The standard pool price was overriding the user-typed value. I have fixed this issue.
- https://sharing.clickup.com/36619926/t/h/863gue9bj/DRUJXZ8UOZ81NC3
> fix: standart pool price override issue

- src/components/TextInput/TextInput.tsx
- The "Enter/Return" key was not functioning properly on mobile devices' keyboards. I have resolved this issue.
- https://app.clickup.com/t/866a6zw33
> fix: enter - key issue on mobile devices fixed

- src/components/Pools/PoolList/PoolCardListView.tsx
- src/components/Pools/PoolList/PoolListV2.tsx
- src/components/Pools/PoolList/PoolListV3.tsx
- Fixed evmos infinity loading in pool page, it should show "not active rewards"
https://app.clickup.com/t/866aabmuz
> fix: evmos infinity loading in pool page

- src/components/Elixir/DetailModal/IncreasePosition/index.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- User can be able to increase liquidity. I've fixed the Wrapped/Native token issue.
- Elixir audit warning text
- https://app.clickup.com/t/862jw5e0x
- https://app.clickup.com/t/866abqge4
> fix: increase liquidity currency issue

- src/state/pstake/hooks/common.ts
- Fixed the order of extra rewards of farm, the order of extra rewards from farms with more than 2 tokens as extra rewards is being shown wrong, this makes users see rewards from a token when it should be rewards from another token
https://app.clickup.com/t/864eqwu1u
> fix: extra farm rewards showing wrong

- src/components/Button/styles.tsx
- Fixed button hidden the dropdown values
https://app.clickup.com/t/866abr399
- Before
- After
> fix: button z-index hidden the dropdown

- src/components/SwapWidget/MarketOrder/index.tsx
- src/components/SwapWidget/SwapDetailInfo/index.tsx
- Fixed texts overflow in swap widget
https://app.clickup.com/t/866acfaff
> fix: texts overflow in swap widget

- src/components/SwapWidget/MarketOrder/index.tsx
- Clear input when change the token
https://app.clickup.com/t/866acfcfm
> fix: clear input when change the token

- src/components/Governance/Detail/VoteModal/index.tsx
- src/components/Governance/Detail/VoteModal/styleds.tsx
1. Vote Modal SarNft scroll issue 
2. Add padding after title 
3. Make Uppercase for Vote Case FOR / AGAINST
https://app.clickup.com/t/860qubhcc?comment=90060017244051
> fix: bug hedera governance

- src/components/WatchList/CurrencyPopover/index.tsx
- Fixed the scroll issue in watchlist
https://github.com/bvaughn/react-window#why-is-my-list-blank-when-i-scroll
https://app.clickup.com/t/866abqugw?comment=90090022138578
> fix: scroll issue in watchlist

- src/components/Governance/Detail/VoteModal/index.tsx
- src/components/Governance/Detail/VoteModal/styleds.tsx
- Add Error handling when vote transaction fails
> fix: hedera governance error handling

- src/components/WalletModal/index.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- Fixed no found chains message in wallet modal
> fix: no found chains message in wallet modal

- src/state/psarstake/hooks/hedera.ts
- src/utils/hedera.ts
- Disabled rent on single stake
> feat: disable rent

- package.json
- src/state/psarstake/hooks/hedera.ts
- src/utils/hedera.ts
> Merge Main Into Dev

- src/hooks/Trades.ts
- Fixed elixir trade to reset when the value is invalid
https://app.clickup.com/t/866ag5eeq
https://app.clickup.com/t/866ag5aj1
https://app.clickup.com/t/866ag5eqg
https://app.clickup.com/t/866agb5af
> fix: elixir trade not reseting

- src/components/Pools/Stake/index.tsx
- src/components/SwapWidget/SelectTokenDrawer/styled.ts
- src/components/WatchList/CurrencyPopover/index.tsx
- Added "not found" message on watchlist
- Fixed text overflow in select token drawer
- Fixed decimal issue with small lp amount when change the percentage 
https://app.clickup.com/t/866agb59f
https://app.clickup.com/t/866agb5ea
https://app.clickup.com/t/866agb5rc
> fix: bugs related with watchlist and token drawer

- src/components/Airdrop/HederaAirdrop/abis/registrationCompliant.json
- src/components/Airdrop/HederaAirdrop/hederaAirdrop.stories.tsx
- src/components/Airdrop/HederaAirdrop/index.tsx
- src/components/Airdrop/HederaAirdrop/styles.tsx
- src/components/Airdrop/index.tsx
- src/components/index.ts
- It incorporates a function that allows for the collection of user Hedera accounts.
- https://app.clickup.com/t/86698pcme
> feat: hedera airdrop registration process

- src/hooks/Trades.ts
This PR revert changes of https://github.com/pangolindex/components/pull/443
> fix: swap widget hang issue due to infinite re-rendering

- src/components/Pools/PoolCard/PoolCardView.tsx
- src/components/Pools/Stake/index.tsx
- Fixed the signature don't is requested if the user change the percetage
- Fixed the apr not is showing for some farms
- https://app.clickup.com/t/866aghr2q
- https://app.clickup.com/t/866agb5kk
> fix: bugs related with farm aprs and signature

- src/components/SarManageWidget/Claim/index.tsx
- Fixed the claim is activating 2 times
https://app.clickup.com/t/866aex759?comment=90090023363540&threadedComment=90090023592981
> fix: only active claim one time

- src/apollo/elixirPools.ts
- src/components/Elixir/PoolList/PoolCard/index.tsx
- src/components/Elixir/PoolList/PoolCard/styles.tsx
- src/components/Elixir/PoolList/PoolCard/types.tsx
- src/components/Elixir/PoolList/index.tsx
- src/components/Elixir/PoolList/poolList.stories.tsx
- src/components/Elixir/PoolList/styles.tsx
- src/components/Elixir/PoolList/types.tsx
- src/components/Elixir/Sidebar/types.tsx
- src/components/Elixir/index.tsx
- src/hooks/elixir/hooks/evm.ts
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- Elixir All Pool whose liquidity > 0
- https://app.clickup.com/t/866agma9y
> feat: elixir all pool list

- src/components/Pools/PoolImportModal/PoolImport/index.tsx
- src/components/WalletModal/index.tsx
- Show pangolin is live chains in first on wallet modal
- Fixed infinity loop in useEffect in pool import
https://app.clickup.com/t/866ajebjy
https://app.clickup.com/t/866ahq7je
> fix: bugs related with wallet modal and pool import

- src/connectors/HashConnector/index.ts
- src/state/pmulticall/updater.tsx
- Replaced hedera rpc
- Increase hedera chunk size
- Added gas limit in multicall calls
> feat: replace hedera rpc

- example/package.json
- example/yarn.lock
- package.json
- src/components/NetworkSelection/index.tsx
- src/components/Pools/PangoChef/EarnDetail/index.tsx
- src/components/Pools/PoolImportModal/PoolImport/index.tsx
- src/components/WalletModal/index.tsx
- src/components/WatchList/WatchList.tsx
- src/components/WatchList/styleds.tsx
- src/hooks/elixir/hooks/index.ts
- yarn.lock
- #462 
- #463 
- #465 
- #466
> Production v7.3.2

- src/components/Bridge/BridgeInputsWidget/index.tsx
- src/hooks/useApproveCallback/evm.ts
- src/hooks/useApproveCallback/hedera.ts
- src/state/pbridge/hooks.ts
- Fixed approval state to change approve instantly
- Reset bridge swap inputs when change the selection
https://app.clickup.com/t/866ag5f21
https://app.clickup.com/t/866akj9vf
> fix: change approve instantly and bridge swap

- package.json
- src/components/Elixir/DetailModal/IncreasePosition/index.tsx
- src/locales/de.json
- src/locales/en.json
- src/locales/es.json
- src/locales/fr.json
- src/locales/pt-br.json
- src/locales/tr.json
- src/locales/vn.json
- src/locales/zh.json
- src/state/pburn/elixir/evm.ts
- Updated `Remove liquidity` notification text and currency detail.
- Added `Insufficient Token balance` check mechanism.
- https://app.clickup.com/t/866afcuku
- https://app.clickup.com/t/866afnj55
- <img width="341" alt="Screenshot 2023-06-23 at 16 25 36" src="https://github.com/pangolindex/components/assets/6755848/1d710807-ae0a-4973-87ed-35a8cedef3ff">
> fix: elixir bugs related to add/remove liq

- src/components/SwapWidget/MarketOrder/index.tsx
- src/hooks/useApproveCallback/hedera.ts
> fix: approve whbar issue

- src/components/SarManageWidget/Claim/index.tsx
- src/components/SarManageWidget/ConfirmDrawer/index.tsx
- src/components/SarManageWidget/ConfirmDrawer/styled.ts
- src/components/SwapWidget/MarketOrder/index.tsx
- src/hooks/useApproveCallback/evm.ts
- src/hooks/useApproveCallback/hedera.ts
- Fixed approve lint
- Added fallback case the use approve small amout of requested
- Fixed overflow in sar stake error
- Fixed swap widget showing infinite loading message 
https://app.clickup.com/t/866am9gue
https://app.clickup.com/t/866akuwhd
> fix: approve bug & swap widget loading message

- src/state/papplication/atom.ts
- Save use subgraph in localstorage
> fix: save use subgraph in localstorage

- src/stories/introduction.stories.mdx
- Fixed instructions how to install and use this package, #482
> fix: installation instructions

- src/components/Pools/ClaimReward/index.tsx
- src/components/Pools/PangoChef/ClaimReward/index.tsx
- src/components/Pools/PangoChef/Compound/index.tsx
- src/components/Pools/PangoChef/Stake/index.tsx
- src/components/Pools/RemoveFarm/index.tsx
- src/components/Pools/Stake/index.tsx
-  Fixed miexpanel error in  properties
> fix: mixpanel errors

- src/hooks/useApproveCallback/hedera.ts
- Fixed hedera approve issue for amount greather than token total supply
> fix: hedera approve issue for amount greather than total supply

- src/components/Pools/DetailModal/Details/index.tsx
- src/components/Pools/index.tsx
- src/components/Stat/Stat.tsx
- src/constants/index.ts
- Added analytics page url mapping
- Fixed show infinite loading in superfarm tab
> fix: fix analytics page url & infinite loading in superfarms tab

- src/components/Pools/index.tsx
- src/state/ppangoChef/hooks/dummy.ts
- src/state/ppangoChef/hooks/evm.ts
- src/state/pstake/hooks/dummy.ts
- Added some useMemo to fix re-render in pool page
> fix: re-render the pool page

- src/components/Pools/PangoChef/Stake/index.tsx
- src/hooks/useApproveCallback/hedera.ts
- Fixed approve bug in hedera returning not approved forever
> fix: approve bug in hedera

- src/components/Elixir/AddLiquidity/ConfirmDrawer/index.tsx
- src/components/Elixir/AddLiquidity/index.tsx
- src/components/Elixir/DetailModal/IncreasePosition/index.tsx
- src/components/Elixir/index.tsx
- src/state/pburn/elixir/evm.ts
- Add liquidity successful flow changed
- Fixed remove liquidity message
- Fixed dynamic data issues on the detail tab component.
-
- https://app.clickup.com/t/862k5mtct
- https://app.clickup.com/t/866afcwg1
- https://github.com/pangolindex/components/assets/6755848/5f0fdf75-ef19-4644-9cdf-aadba426bcf2
- 
- https://github.com/pangolindex/components/assets/6755848/dd320fdf-e0f6-4cc6-9a91-cbe295085884
> fix: elixir bugs

- example/src/layout/Header/index.tsx
- src/components/Airdrop/Airdrop/ChangeChain/index.tsx
- src/components/Airdrop/Airdrop/Claimed/index.tsx
- src/components/Airdrop/Airdrop/NotConnected/index.tsx
- src/components/NetworkSelection/index.tsx
- src/state/papplication/atom.ts
- src/state/papplication/hooks.ts
- src/utils/wallet.ts
- Fixed airdrop when request to change chain to open wallet modal
- https://app.clickup.com/t/866amumrg
> fix: airdrop when request to change chain to open wallet modal

- src/components/Pools/index.tsx
- Fixed "your farms" tab not showing
> fix: "your farms" tab not showing

- src/components/Elixir/DetailModal/EarnWidget/index.tsx
- Tooltip added to "Earn section"
- https://app.clickup.com/t/866am9nah
- https://github.com/pangolindex/components/assets/6755848/4a0d4c9c-0684-497e-9c3f-505d9dc3a000
> fix: add tooltip elixir earned section

- src/locales/es.json
- Fixed your farms translation in spanish
> fix: your farms translation in spanish

- src/components/Elixir/DetailModal/IncreasePosition/index.tsx
- Fixed border radius in increase liquidity
> fix: border radius in increase liquidity

- src/components/Elixir/DetailModal/EarnWidget/Remove/index.tsx
- src/components/Elixir/DetailModal/EarnWidget/index.tsx
- Fixed White Screen Issue
- Reset Stepper after successful removal.
- https://app.clickup.com/t/866apt7jx
- https://app.clickup.com/t/866afcwg1
-
- https://github.com/pangolindex/components/assets/6755848/8b8c193b-2f73-4ae5-acd1-c7b5207437ee
> fix(elixir): white screen and stepper issue

- src/components/Elixir/DetailModal/Tabs/DetailTab/index.tsx
- Increased value threshold on Detail Tab.
- https://app.clickup.com/t/866afctt3
> fix(elixir): increase value threshold in detail tab

- package.json
- src/state/pbridge/providers/squid.ts
- yarn.lock
- Updated several package versions
- Squid -> https://security.snyk.io/vuln/SNYK-JS-VM2-5415299
- Luxon -> https://security.snyk.io/vuln/SNYK-JS-LUXON-3225081
> fix: updated squid and luxon versions

- monorepo/packages/shared/package.json
- monorepo/packages/shared/src/hooks/index.ts
- monorepo/packages/shared/src/hooks/web3React.ts
- Added useActiveWeb3React hook in shared package
> feat: added active web3 react 

- monorepo/package.json
- monorepo/packages/walletmodal/package.json
- monorepo/patches/@web3-react+core+6.0.9.patch
- monorepo/yarn.lock
- add patch packages for `@web3-react/core`
> fix(monorepo): add patch package to monorepo example

- src/constants/swap.ts
- Changed swap default currency
https://app.clickup.com/t/861mu4jj4
> fix: change swap default currency

- src/state/pstake/hooks/evm.ts
- src/state/pstake/hooks/index.ts
- Add  Avalanche Minichef switch hook For Subgraph and Contract
> fix: add switch (subgraph/contract) for avalanche minichef hook

- package.json
- yarn.lock
- Update sdk to change the compound to new farm in flare
> fix: update sdk to 5.3.6
